### ISSUE TITLE
Big Save Objects

### ISSUE THREAD

**Issue by robbobfrh84** [matthewmain/kiss_the_sky#70]
There could be both a frontend / backend solution to this...

### For frontend I found this...
- https://github.com/floydpink/lzwCompress.js 

### For backend (Both compress and decompress)
- CJSON
  - https://www.npmjs.com/package/jsonc add to react to handle circular references...?
- RSON

### Other stratagies ... 
- Maybe... you can only save your seeds? .... at year end..? That would leave only the object's genome, then on unsaved they get randomly sown again? 
  - ...Maybe you get one live in-game save.... then, just the end of year seeds for additional saves.

### Other tools/ideas

Json minified
- https://codebeautify.org/jsonminifier - Just for getting an idea, there is this UI. Not sure what it's using but good for testing copy paste to see what can be shrunk.

**Comment by matthewmain** [comment]
Just adding a note here about the numerous floats in the raw JSON. I experimented with truncating the x/y point values, but they're processed so frequently (velocity, verlet span refinement, bounce constraints, gravity, etc.) that rounding the decimals at every calculation starts to affect the performance and also destabilizes the physics pretty quickly. So I think the current calculations and floats, unfortunately, are going to have to stay. 

But I think that, alternatively, running through the JSON at save time and truncating all the x/y float values to the third decimal would work. Restarting a saved game with values rounded to thousandths should keep the physics stable, and omitting ten decimals for every float should have a significant effect on the JSON size.

(Also, just a note, the actual JSON seems to be much less than the Chrome console estimate. For example, when I tested by stringifying the point array with ~50 plants, Chrome said ~650KB. But when I copied the JSON to a text file, the file on macOS Finder said it was only ~320KB. So the data may be much less than I'd orginally thought.)

**Comment by matthewmain** [comment]
I've been experimenting a little with custom JSON compression, and I think we could reduce a LOT of data by writing a pair of compression/decompression functions that rely on .replace() with regex. 

As an example, I wrote this to reduce all the floats to three decimal places:

`<string>.replace( /\d*\.\d+/g, ( float ) => { return ( Math.round( float * 1000 ) / 1000 ) } );`

Running it on the raw stringified points collection JSON reduces the file size to 75% of the original, which is a good start. 

The rounded floats should be able to just be passed back into the game as-is when the game is resumed. But I think a similar method could also be used to encode and decode references to objects. For example, a compression function could replace all stringified object references with short unique placeholders that encode the objects's class and id. (Something like "#P56#" could replace a reference to an entire point object with an id of 56.) Then, when the saved game is called back up, a decompression function could first re-populate the object collection arrays, then replace all of the encoded reference placeholders with the object itself by looking it up in the arrays by id.

To go even further, if needed, maybe even some of the common wordy key/value pairs (like '"materiality":"material"') could be encoded and decoded as well.

**Comment by matthewmain** [comment]
@robbobfrh84  Okay, so I've been digging deeper into how to save/retrieve game data. I ran into a potential issue with stringification generally. JSON doesn't support variable references. So when you stringify a variable that references an already-existing array or object and then parse it back as javascript, that variable's value becomes a new unique array or object instead of a reference to the original array or object. You may have already known this, but I hadn't really realized that. :/

So I guess for my own understanding before moving forward, I have a couple of questions about Mongo. First, I think you mentioned this in our call, but what is the purpose of stringifying the data? Does it need to be stringified in order to be saved to a Mongo database? And I guess the second question is whether it's possible to save raw javascript to a Mongo db? Like, for example, do you know if there's an option to save a javascript object directly to the db without stringifying it?

**Comment by robbobfrh84** [comment]
It's actually the request from front to back end that requires it to be a string. But... axios handles the stringing for all of our operations right now... I wonder if it'll draw an error when we actually attempt to use it... 

I also wonder if this could be useful. It'd prob be easier to install it was a react dependency to try. 
* https://www.npmjs.com/package/jsonc 

However, on the Mongo side, I actually wanted to test saving an object to mongo, because after doing a little research i found out that it might not take up nearly as much space the way mongo saves it because its actually saved as an object.  

----

On another note... I was thinking about this from a gaming perspective and wanted to get your thoughts... What about not being able to save the game, but, being able to save your seeds. That way, we'd only need the seeds DNA and we could ignore all other parts of the game. Like you'd just be saving the last year's seeds. Kinda like getting to a checkpoint in a game... i BET that early game development had this same issue. I know this would take some re-thought on implementations of game flow.

Just a thought, I was thinking about doing something like this later on. But maybe it's an easier route, looking at these issues we're having now.  

----

I think after I get this new login / signup flow plugged in I'll checkout trying to pass the object through axios and see what happens. I also wonder what happens with the cjson added.

**Comment by matthewmain** [comment]
Ah, gotcha, thanks, that explains it. So looks like we'll need to handle stringified JSON at some point regardless. Good to know. 

Just saving the seeds makes a lot of sense. It would definitely be a way to avoid wrestling with all the data that would be required for a snapshot-style save. It would actually be a step in the direction of something I'd wanted to do in a later version--being able to pick up seeds and drag them to some storage area for later use.

I guess my feeling is that if we CAN get snapshot saving to work now, that would be the ideal option--just in terms of fluid UX and not having to work out how to implement winter seed-saving functionality into the game flow. But if snapshot saving turns out to be a real obstacle, then seed-saving would be a good plan B? What do you think? If you feel like seed-saving would be the most ideal anyway, we can just start to build that out and not worry about snapshot saving. But if you think it's worth trying to give snapshot saving a go first, then I'd be happy to take on the JSON parsing project. Would be a challenge, but I already know how all of the objects reference each other, and I think I could probably write a custom parser that uses codified placeholders and re-assigns the references. That would compress the data too.  We'd have to work together to plug everything into a "resume game" function that calls the database and runs the parser, but I think it's doable? 

I did check out that JSON parsing library--I don't _think_ it preserves references, but I'll dig into the source code a bit more and see what it does. Would be great if it has something that could help.  (Of course, if you find out the axios can handle objects, then there's no problems anyway, haha.)

What do you think?

**Comment by robbobfrh84** [comment]
So just a testing update... I hooked up the `/api/user/save` endpoint to save an object. 
- ...waited a few years to get a larger obj. 
- paused the game and logged the stringify which was (11.8mb)
  - So, didn't do anything to size it down. just the normal state with long strings. 
- then executed the save api. 
- looks like Axios handles the stringification on its own. That's good!
- I was able to get through as an index and saved to the users db 
- The size for the stored object was 4.8mb. 
- That's really not too bad of a start. We know we can get it down quite a bit if we round and map the variable names. 
- Think i'll try and complete the cycle with a raw display of saved games for testing the "resume". 
- Getting it working with the large files locally first will be a good place to start as we move to pair it down after that.

**Comment by matthewmain** [comment]
I think I've got all of the formatting, referencing, and compression issues pretty much resolved with [this PR](https://github.com/matthewmain/kiss_the_sky/pull/76). See the PR notes for details, but saving/resuming is now working locally with data that's mostly under 1MB. So should be ready to set everything up with the db!

**Comment by robbobfrh84** [comment]
Great! I'll see if i can't get a raw db save/resume update for testing soon. 
- Also, I saved your notes from the PR and added them to a card in the project board

**Comment by robbobfrh84** [comment]
Update after a few (24) saves to the db. For some reason I can't get the size of each entry at this point. i actually think i need to write it as a mongodb query to get the size. 
- However, looks like the entire db is at most ~8mb 
- So, with 24+ saves that pretty small for now. Also, I know we can compress (.zip) these objects as well. I think that's pretty workable at this point.

**Comment by matthewmain** [comment]
That's pretty good! I guess we could try to cap the number of saves a user can have at once if it becomes an issue, but seems like it should be fine for now.

Do you have any idea how much total db storage heroku offers for this tier?

**Comment by robbobfrh84** [comment]
It's not a lot, 512mbs. I was thinking it might be worth updating heroku now to test and see how much it'll eat up. 512 is good enough for us to mess around with, though. 

I was also thinking of adding a `download` game (as a .json) and upload button - just for development. So, We can share testing points/examples in the game. It shouldn't be too hard to add and probably worth it if we're likely going to be needing to clear the mongoDB. 

Oh,  and Heroku Uses mLabs > https://mlab.com/plans/pricing/

**Comment by matthewmain** [comment]
Ah yeah that's not much--but still plenty to play with until more than handful of people actually started signing up and saving games, and plenty for development. Maybe we could split the cost of Heroku and mLabs if we decide to upgrade down the road. 

The dev json download option is a great idea. And yeah, might be a good point to push to heroku to see how it works with the remote db with the data size we've got now.

**Comment by robbobfrh84** [comment]
Ok, So, I've been a bit distracted by a bunch of ways to make our saved objects even smaller. What I discovered in my digging was that a lot of ways I been messing around with kinda already have been added into how Mongo saves objects strings like the ones we've been storing. 

I was thinking about using the `zlib` library which will compress the .json file down to about 10-15% of the original size. Which I felt was kinda worth implementing. But, it looks like mongo already does something similar that gets them down nearly that size by default... This image doesn't show it but `WT/Snappy` is the default compression being use.

<img width="682" alt="Screen Shot 2019-05-21 at 7 11 55 PM" src="https://user-images.githubusercontent.com/15821138/58138778-6a303f80-7bfd-11e9-9891-2f2bc8474ae8.png">

So, as I added as many as 30 saved games to the DB, it wasn't really seemingly adding up. In a good way that the total storage the DB was taking up wasn't nearly the addition of all the saved game size. So, the game sizes are the size once they are `PULLED` from DB and decompressed. They sit there much smaller... 

End of the day it looks like `large` games fall in the 50-150kb range... at this point.... as far as I can tell 🤷‍♂️

Seems having a bunch of users using it and checking the growth could be the best way to figure out what to do!

**Comment by matthewmain** [comment]
That's great! At the top of this thread we were dealing with many MBs of data, so this is now a huge reduction. With these numbers, we'd need a lot of active users (probably many hundreds?) before even the sandbox mlabs DB started to approach capacity.  We can keep an eye on how much data accumulates, but looks like for the foreseeable future we'll be in good shape. I'd say this issue is resolved.

**Comment by robbobfrh84** [comment]
Also, I think using AWS or Google Cloud Bucket storage makes since to save the games as .json files there, where you'll get a ton more free space. I added a note about that for the next sprint to explore. 

Let's close this sucka!
